auth:
  - user: iompi
    group: iompi
    uid: ${IOMPI_UID-1000}
    gid: ${IOMPI_GID-1000}
    password: ${IOMPI_PASSWORD-iompi}

global:
  - "force user = iompi"
  - "force group = iompi"

share:
  - name: data
    path: /samba/data
    browsable: yes
    readonly: no
    guestok: no
    validusers: iompi
    writelist: iompi
    veto: no